INSERT INTO persona (
    Nombre,
    Apellido_Paterno,
    Apellido_Materno,
    CURP,
    Genero,
    Fecha_De_Nacimiento,
    Tipo_De_Sagre,
    Numero_De_Emergencia,
    Numero_De_Telefono,
    Nacionalidad,
    Correo_Electronico,
    Rol
) VALUES (
    'Admin',
    'Sys',
    '',
    '',
    'Masculino',
    '2001-10-08',
    'O+',
    3487895811,
    3481098523,
    'Mexicano',
    'administrador@gmail.com',
    'Administrativo'
);

INSERT INTO credenciales(
    FK_Persona,
    Correo,
    Contraseña
) VALUES (
    'f7dc455f-4375-11ee-96d4-0800274fe67a',
    'administrador@gmail.com',
    '5914af360a493b7cd046d15bc04c0b9f'
)

INSERT INTO administrativos (
    FK_Persona,
    NSS,
    Fecha_De_Contratacion
) VALUES (
    'f7dc455f-4375-11ee-96d4-0800274fe67a',
    'NOT-NECESARY',
    '2023-08-25'
)


insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Willie', 'Keson', null, '84-189-2962', 'Masculino', '2022-10-01', 'O', '9495186843', '8318237120', 'Mexicano', 'wneylon0@gmpg.org', 'Padre', false, 'https://robohash.org/consequaturaliasitaque.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Orton', 'Benzies', 'Filippucci', '71-831-3095', 'Masculino', '2022-10-01', 'AB+', '6541195208', '2571420522', 'Mexicano', 'ofilippucci1@webnode.com', 'Administrativo', false, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Ezra', 'De Ferraris', 'Apperley', '25-379-8729', 'Masculino', '2022-10-01', 'A-', null, '1439301909', 'Mexicano', 'eapperley2@themeforest.net', 'Profesor', false, 'https://robohash.org/distinctiofugaaliquid.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Nestor', 'Bartelli', null, '89-267-8655', 'Masculino', '2022-10-01', 'A-', '9329695428', '4046025888', 'Mexicano', 'nrosenfelt3@php.net', 'Estudiante', false, 'https://robohash.org/accusamusnemolaboriosam.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Blondy', 'Selley', 'Plaster', '69-988-3678', 'Femenino', '2001-09-10', 'A', '8907395205', '8899136068', 'Mexicano', 'bplaster4@techcrunch.com', 'Padre', true, 'https://robohash.org/impeditdoloraut.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Raff', 'Dibley', 'Hansmann', '34-929-8001', 'Masculino', '2022-10-01', 'O-', null, '3566465060', 'Mexicano', 'rhansmann5@nationalgeographic.com', 'Profesor', false, 'https://robohash.org/saepererumnumquam.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Cookie', 'Abelson', null, '50-586-7058', 'Femenino', '2001-09-10', 'A+', '2138425539', '3927785463', 'Mexicano', 'cnasey6@bizjournals.com', 'Padre', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Genna', 'Dei', 'Seide', '97-906-9087', 'Femenino', '2001-09-10', 'AB', '3863769693', '9093038252', 'Mexicano', 'gseide7@cnbc.com', 'Padre', true, 'https://robohash.org/architectobeataerepellendus.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Julie', 'Sibbs', null, '42-781-4652', 'Femenino', '2001-09-10', 'B-', null, '4722755238', 'Mexicano', 'jrustan8@issuu.com', 'Profesor', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Bogart', 'Primrose', 'Farny', '28-001-5593', 'Masculino', '2022-10-01', 'A-', '8352219541', '5442055230', 'Mexicano', 'bfarny9@google.de', 'Profesor', true, 'https://robohash.org/aliquidautemenim.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Dudley', 'Eastam', 'Khidr', '02-690-6789', 'Masculino', '2022-10-01', 'A+', '6195115158', '2583654347', 'Mexicano', 'dkhidra@illinois.edu', 'Administrativo', true, 'https://robohash.org/inestvoluptatibus.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Rock', 'Simonato', 'Common', '22-066-5056', 'Masculino', '2022-10-01', 'O+', null, '9381167825', 'Mexicano', 'rcommonb@java.com', 'Profesor', true, 'https://robohash.org/dolornamquas.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Gui', 'MacMurray', 'Loxton', '55-304-6417', 'Femenino', '2001-09-10', 'AB-', '9991409743', '5453603578', 'Mexicano', 'gloxtonc@ftc.gov', 'Administrativo', true, 'https://robohash.org/accusamusimpeditminima.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Jinny', 'Fargher', null, '83-367-8726', 'Femenino', '2001-09-10', 'B+', '6283904946', '6215144842', 'Mexicano', 'joxburyd@clickbank.net', 'Estudiante', false, 'https://robohash.org/minimaculpacorporis.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Tannie', 'Merritt', null, '76-076-7685', 'Masculino', '2001-10-01', 'AB-', '7525060458', '4746207531', 'Mexicano', 'tarbucklee@plala.or.jp', 'Administrativo', false, 'https://robohash.org/eligendieiusex.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Abdul', 'Arrigo', 'Peters', '61-575-2100', 'Masculino', '2022-10-01', 'A+', '4648648040', '7043415172', 'Mexicano', 'apetersf@uol.com.br', 'Estudiante', true, 'https://robohash.org/voluptatemeiussapiente.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Moyra', 'De Bischof', null, '58-240-1122', 'Femenino', '2001-09-10', 'B', null, '2932145949', 'Mexicano', 'mjerzykg@ca.gov', 'Profesor', false, 'https://robohash.org/molestiaequilaborum.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Marlon', 'Semon', 'Winny', '38-362-5816', 'Masculino', '2022-10-01', 'O-', '1824668463', '9362324348', 'Mexicano', 'mwinnyh@vinaora.com', 'Profesor', false, 'https://robohash.org/temporeinet.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Michale', 'Thickpenny', 'MacGaughie', '49-364-1146', 'Masculino', '2022-10-01', 'B+', '8694339919', '9787087589', 'Mexicano', 'mmacgaughiei@lulu.com', 'Estudiante', false, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Hogan', 'Ackery', null, '12-102-7769', 'Masculino', '2022-10-01', 'O-', '3576888135', '8943433965', 'Mexicano', 'hsterrickerj@cloudflare.com', 'Profesor', true, 'https://robohash.org/beataecommodiest.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Kore', 'McKyrrelly', 'Hover', '76-532-0483', 'Femenino', '2001-09-10', 'AB', '9261355243', '5634386056', 'Mexicano', 'khoverk@princeton.edu', 'Estudiante', true, 'https://robohash.org/ametconsequunturconsequatur.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Sybil', 'Caslin', 'Calloway', '75-089-8691', 'Femenino', '2001-09-10', 'A-', '4331599862', '5655258788', 'Mexicano', 'scallowayl@netlog.com', 'Profesor', true, 'https://robohash.org/totamquisnon.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Tamas', 'Woodage', 'Balchen', '99-396-7787', 'Masculino', '2022-10-01', 'O', '8032860255', '5345742476', 'Mexicano', 'tbalchenm@youku.com', 'Estudiante', true, 'https://robohash.org/quiaccusantiumet.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Bentley', 'Gregon', 'Bushby', '31-856-2405', 'Masculino', '2022-10-01', 'B+', null, '7753774825', 'Mexicano', 'bbushbyn@boston.com', 'Padre', true, 'https://robohash.org/delenitimaioresquas.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Blondell', 'Palay', null, '07-391-3974', 'Femenino', '2001-09-10', 'O', '9555889735', '6176934100', 'Mexicano', 'bkibblewhiteo@google.com.br', 'Padre', false, 'https://robohash.org/quonemoipsam.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Delilah', 'Kits', 'Smedmoor', '98-237-3222', 'Femenino', '2001-09-10', 'B+', null, '4706550261', 'Mexicano', 'dsmedmoorp@admin.ch', 'Padre', true, 'https://robohash.org/rerumsimiliqueatque.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Abbi', 'Matthius', 'Lockley', '10-230-7141', 'Femenino', '2001-09-10', 'AB-', '9904270103', '6122634359', 'Mexicano', 'alockleyq@cargocollective.com', 'Padre', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Binky', 'Gullberg', 'Leonardi', '59-203-8917', 'Masculino', '2022-10-01', 'O', null, '2127973619', 'Mexicano', 'bleonardir@360.cn', 'Padre', true, 'https://robohash.org/veronihilsed.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Ches', 'Mayman', null, '92-235-3948', 'Masculino', '2022-10-01', 'AB+', '1274963121', '8354568994', 'Mexicano', 'cbellays@networksolutions.com', 'Padre', true, 'https://robohash.org/perferendisautest.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Fidelity', 'Hymas', null, '17-030-1907', 'Femenino', '2001-09-10', 'A+', '6816428222', '3468815184', 'Mexicano', 'fsarfattit@smh.com.au', 'Padre', false, 'https://robohash.org/repudiandaemollitialaborum.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Candace', 'Morgans', 'Wavish', '24-943-9122', 'Femenino', '2001-09-10', 'B', '4451366032', '6523717263', 'Mexicano', 'cwavishu@shop-pro.jp', 'Padre', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Byrle', 'Agglio', 'Wallett', '63-333-4522', 'Masculino', '2022-10-01', 'AB', null, '2022801768', 'Mexicano', 'bwallettv@last.fm', 'Administrativo', false, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Christabel', 'Baert', 'Feetham', '59-855-1729', 'Femenino', '2001-09-10', 'O+', '7236796894', '6502855055', 'Mexicano', 'cfeethamw@ucoz.ru', 'Profesor', false, 'https://robohash.org/autetet.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Gaile', 'Ferrick', 'Scrauniage', '27-197-1242', 'Masculino', '2022-10-01', 'O+', '4694718616', '1279749858', 'Mexicano', 'gscrauniagex@comcast.net', 'Estudiante', true, 'https://robohash.org/doloremdoloremerror.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Marcella', 'Roycroft', null, '47-887-2307', 'Femenino', '2001-09-10', 'AB', null, '2773937431', 'Mexicano', 'mdufaury@china.com.cn', 'Estudiante', false, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Karin', 'Trembey', null, '29-987-9500', 'Femenino', '2001-09-10', 'B+', '2649457293', '2835107393', 'Mexicano', 'kkalinovichz@europa.eu', 'Estudiante', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Sylas', 'Anster', 'Arnall', '99-142-1456', 'Masculino', '2022-10-01', 'AB-', '3125778631', '3136513833', 'Mexicano', 'sarnall10@naver.com', 'Padre', false, 'https://robohash.org/essesuscipitut.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Reamonn', 'Tumayan', 'Altamirano', '68-244-8179', 'Masculino', '2022-10-01', 'B+', '6975157130', '7652498288', 'Mexicano', 'raltamirano11@usa.gov', 'Padre', true, null);
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Tull', 'Matushenko', 'Geraldini', '06-003-7624', 'Masculino', '2022-10-01', 'AB+', null, '9105013451', 'Mexicano', 'tgeraldini12@unicef.org', 'Administrativo', false, 'https://robohash.org/idvoluptatemea.png?size=50x50&set=set1');
insert into persona (Nombre, Apellido_Paterno, Apellido_Materno, CURP, Genero, Fecha_De_Nacimiento, Tipo_De_Sagre, Numero_De_Emergencia, Numero_De_Telefono, Nacionalidad, Correo_Electronico, Rol, Active, Imagen) values ('Connie', 'Hewins', null, '16-859-9392', 'Masculino', '2022-10-01', 'A', null, '1279006966', 'Mexicano', 'cbourbon13@netscape.com', 'Profesor', false, 'https://robohash.org/pariaturhicet.png?size=50x50&set=set1');